version: '3'
services:
    send:
        build:
            context: ./containerA
            dockerfile: Dockerfile            
            args:
                PYTHON_VERSION: ${PYTHON_VERSION_ARG}
        volumes:
            - ./dataJson:/data
            - ./logsA:/log
        links:
            - receive
        depends_on:
            - receive
        container_name: send-neueda

    receive:
        build: 
            context: ./containerB
            dockerfile: Dockerfile            
            args:
                PYTHON_VERSION: ${PYTHON_VERSION_ARG}
        ports:
            - "5000:5000"
        expose:
            - 5000
        volumes:
            - ./dataXml:/data
            - ./logsB:/log
        container_name: receive-neueda
        


# volumes:
#     data:
#         external: true
