version: '3'
services:
    send:
        build: ./containerA
        volumes:
            - ./dataJson:/data
        links:
            - receive
        depends_on:
            - receive

    receive:
        build: ./containerB
        ports:
            - "5000:5000"
        expose:
            - 5000
        volumes:
            - ./dataXml:/data


# volumes:
#     data:
#         external: true
